### PR TITLE
Update geolink-formatter to support new schema version 1.1.1

### PR DESCRIPTION
**Pull request by kdeininger**

### CODE REVIEW

**Comment by pfirpfel** [comment]
Are there no changes to /tests/resources/geolink_v1.1.1.xml because of the new schema?

**Comment by kdeininger** [comment]
No, the resulting XML output is the same, but the API should be called using the new version.

**Comment by jwkaltz** [comment]
@vvmruder can we simply merge this, or is there any migration / compatibility issue to consider?

**Comment by jwkaltz** [comment]
Done via PR #680

**Pull request merged**
