### PR TITLE
Fix intersection

### PR DESCRIPTION
**Pull request by vvmruder**
We want to try to improve the intersection process in speed and decrease complexity.

#383

### CODE REVIEW

**Comment by jwkaltz** [comment]
@vvmruder yes, I will try to find time tomorrow (it takes some time to adapt, we are still in copy-paste hell in that part)

**Comment by vvmruder** [comment]
Ok. I only want to see if everything works before I merge this :)

**Comment by jwkaltz** [comment]
Summary, as discussed: the contents are mostly identical with these changes.
The only difference is that after the change, "Nutzungsplanung kantonal (Siedlung)" and "Nutzungsplanung kantonal (Strassen)" appear in the TOC under "... welche das Grundstück nicht betreffen, whereas before they appear in "... zu denen noch keine Daten vorhanden sind".
It is not yet clear why there is an impact, and also not yet clear which is actually correct.

Another change is the order of the elements within "Übrige Legende", but this is an already known issue (currently, no sorting imposed here).

**Comment by vvmruder** [comment]
I cross checked it now with our data. And we cant produce a behaviour like you explained @jwkaltz 

So I would merge this now.

**Comment by jwkaltz** [comment]
Makes sense to me @vvmruder . If the order turns out to be incorrect in SZ reports, we will then analyze that more deeply. So merge is fine as far as I am concerned.

**Comment by jwkaltz** [comment]
@vvmruder FYI the newest version (this one) is now in place at Schwyz (development environment), and good news: it turns out the new attribution within the TOC is correct! So the final version of this PR is indeed better than the intermediate version.

**Pull request merged**
