### PR TITLE
some geospatial servers (like Qgis server) doesn't accept decimal numbers as WIDTH and HEIGHT

### PR DESCRIPTION
**Pull request by lopo977**

### CODE REVIEW

**Comment by lopo977** [comment]
Gern geschehen!

**Comment by voisardf** [comment]
I confirm: 
`LookupError: The image could not be downloaded. URL was: https://sitnssl.ne.ch/mapproxy95/service?STYLES=default&LAYERS=plan_cadastral_c2c&SERVICE=WMS&FORMAT=image%2Fpng&REQUEST=GetMap&SRS=EPSG%3A2056&HEIGHT=1169.29133858&WIDTH=2055.11811024&VERSION=1.1.1&BBOX=2552664.04986%2C1216010.701%2C2553395.60914%2C1216426.933&sld=http%3A%2F%2Flocalhost%3A6543%2Foereb%2Fsld%3Fegrid%3D6019076, Response was internal error`

**Comment by voisardf** [comment]
HEIGHT & WIDTH must be int values

**Comment by jwkaltz** [comment]
@lopo977 please merge your pull request, thanks.

**Pull request merged**
