### PR TITLE
Some fix in the legend

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by voisardf** [comment]
tested the fix and there is always a surface indication now... 🤔

**Comment by sbrunner** [comment]
Witch value of area do you have in the getspec for area who isn't an area?

**Comment by voisardf** [comment]
almost, but this error is already in the getspec now:

```
2017-11-15 15:14:20,176 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/oereb/extract/reduced/pdf/706215?getspec=
traceback url: http://localhost:6543/_debug_toolbar/313135333538373638/exception
Traceback (most recent call last):
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid_debugtoolbar\toolbar.py", line 247, in toolbar_tween
    response = _handler(request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid_debugtoolbar\panels\performance.py", line 72, in noresource_timer_handler
    result = handler(request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\tweens.py", line 39, in excview_tween
    response = handler(request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\router.py", line 156, in handle_request
    view_name
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "c:\mapfish\pyramid_oereb\pyramid_oereb\views\webservice.py", line 226, in get_extract_by_id
    request=self._request
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\renderers.py", line 146, in render_to_response
    result = helper.render_to_response(value, None, request=request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\renderers.py", line 458, in render_to_response
    result = self.render(value, system_values, request=request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\renderers.py", line 454, in render
    result = renderer(value, system_values)
  File "c:\mapfish\pyramid_oereb\pyramid_oereb\contrib\print_proxy\mapfish_print.py", line 249, in __call__
    legends[type_][item] += legend[item]
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
```

**Comment by voisardf** [comment]
still there, but further down:
```
2017-11-15 15:57:48,940 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/oereb/extract/reduced/pdf/706215?getspec=
traceback url: http://localhost:6543/_debug_toolbar/313136303535353336/exception
Traceback (most recent call last):
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid_debugtoolbar\toolbar.py", line 247, in toolbar_tween
    response = _handler(request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid_debugtoolbar\panels\performance.py", line 72, in noresource_timer_handler
    result = handler(request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\tweens.py", line 39, in excview_tween
    response = handler(request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\router.py", line 156, in handle_request
    view_name
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "c:\mapfish\pyramid_oereb\pyramid_oereb\views\webservice.py", line 226, in get_extract_by_id
    request=self._request
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\renderers.py", line 146, in render_to_response
    result = helper.render_to_response(value, None, request=request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\renderers.py", line 458, in render_to_response
    result = self.render(value, system_values, request=request)
  File "c:\mapfish\pyramid_oereb\.venv\lib\site-packages\pyramid\renderers.py", line 454, in render
    result = renderer(value, system_values)
  File "c:\mapfish\pyramid_oereb\pyramid_oereb\contrib\print_proxy\mapfish_print.py", line 250, in __call__
    legends[type_][item] += legend[item]
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
```

**Pull request merged**
