### PR TITLE
The Host header should be forwarded

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by voisardf** [comment]
Is that why I get this error on the productif instance for now? 
MaxRetryError("HTTPConnectionPool(host='print', port=8080): Max retries exceeded with url: /print/oereb/buildreport.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07A42AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))",)

**Comment by sbrunner** [comment]
Yes :-/

**Comment by sbrunner** [comment]
New solution proposed :-)

**Comment by sbrunner** [comment]
It's not needed in every cases, it's needed only when we use Apache vhost.
Then I should possible to add it, but I didn't see a good default value.

**Comment by voisardf** [comment]
ok, thanks

**Comment by sbrunner** [comment]
Thanks for the review :-)

**Pull request merged**
