### PR TITLE
relocate print app

### PR DESCRIPTION
**Pull request by jwkaltz**
partially addresses #459

### CODE REVIEW

**Comment by jwkaltz** [comment]
Yes but we do not have a consensus on that yet. So least common denominator right now would seem to at least move the templates into the contribs, because having a top-level "print" directory is confusing (?).

Just a suggestion :)

**Comment by vvmruder** [comment]
Then I would leave it as it was. More confusing is to mix up things more. I still stay on the point that the jasper templates does not have anything to do with the pyramid_project. And therefore I do not want this stuff even deeper in the project.

@voisardf @kdeininger : What's your opinion on this?

**Comment by jwkaltz** [comment]
OK, so I will close this (instead of "verschlimmbessering" things)

**Comment by voisardf** [comment]
I'm late but I do agree :)

**Pull request closed without merging**
