### PR TITLE
first fix for wrong xml rendering

### PR DESCRIPTION
**Pull request by vvmruder**
The XML is malformed and need to be updated.

A big question about this is, on which version we want to rely on.

Compared to the service response provided by canton zürich I found some attributes which already included from the new specification.

These are:
PlanForLandRegisterMainPage in RealEstate
AreaShare/LengthShare in RestrictionOnLandownership

Any suggestions how to deal with it?

### CODE REVIEW

**Comment by vvmruder** [comment]
My personal one is to stay on old version and plan a real switch later.

**Comment by voisardf** [comment]
Hi, for the confederation v 0.4 is absolutely acceptable for now. So I vote for just make it compliant as we have to have it ready on this friday latest... 🙈 :)

**Comment by vvmruder** [comment]
@voisardf Can you confirm, that this version is satisfying your needs?

**Comment by voisardf** [comment]
I'll check this version and let you know!

**Comment by voisardf** [comment]
Looks quite good to me. I did an extract on this base and sent it to Rolf Zuercher for validation. I'll give you the feedback once he gets back to me.
In the mean time I think we could merge this branch and open a new one, if there is bugfixing needed?

Thanks a lot! 👍

**Comment by vvmruder** [comment]
Let us merge this when feedback from rolf is there. It should be enough to merge this evening or tomorrow.

**Comment by voisardf** [comment]
where does the `<script/>` come from? I couldn't find it yet...
And when validating the XML against the schema it says that xsi:type is not valid either...

**Comment by voisardf** [comment]
This one, is the one. Confirmed by the Confederation. Thanks a lot!! 😃

**Comment by kdeininger** [comment]
Finally... :laughing:

The tests should succeed. So I think we can merge this PR when they have finished.

Still OK for you, @sbrunner and @ger-benjamin?

**Comment by sbrunner** [comment]
Looks good to me :-)

**Pull request merged**
