### PR TITLE
Update Report_de.properties

### PR DESCRIPTION
**Pull request by vvmruder**
We have to update FR + IT too

### CODE REVIEW

**Comment by vvmruder** [comment]
@voisardf can you adjust the french part of this change?

**Comment by vvmruder** [comment]
@jwkaltz Why it is not possible to add sbuettler here as reviewer?

**Comment by jwkaltz** [comment]
@vvmruder I assume it is because he does not have sufficient rights to pyramid_oereb, but I myself don't have the access to check or change that. @sbrunner can you please have a look?

**Comment by voisardf** [comment]
@vvmruder : done in PR: https://github.com/camptocamp/pyramid_oereb/pull/456

**Pull request merged**
