### PR TITLE
Fix date format in PDF

### LINKED ISSUE #411: Date format in footer on every page is wrong
In the moment the PDF looks like:
grafik

Specification says:
grafik

### PR DESCRIPTION
**Pull request by kdeininger**
Fixes #411

### CODE REVIEW

**Comment by kdeininger** [comment]
@voisardf @vvmruder 

Should we split the creation date into `CreationDate` and `CreationTime` for easier formatting in the PDF?

**Comment by voisardf** [comment]
@kdeininger : Please merge and check PR https://github.com/camptocamp/pyramid_oereb/pull/400 first before merging this one

**Comment by kdeininger** [comment]
I've added a new `Footer` parameter which is formatted in the Mapfish Print proxy.

The result looks like this now:

image

**Comment by kdeininger** [comment]
So, should we merge this one now or wait for PR #400 being merged? @voisardf

**Comment by voisardf** [comment]
better merge mine first.
but I'm missing you're reviews ;)

**Comment by kdeininger** [comment]
After merging your changes from PR #400, I get the following error:

```
Error while processing request:
net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. java.time.format.DateTimeFormatter cannot be resolved to a type
                value = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy").format(java.time.LocalDateTime.parse(((java.lang.String)parameter_CreationDate.getValue()))); //$JR_EXPR_ID=25$
                        <-------------------------------->
2. java.time.LocalDateTime cannot be resolved to a type
                value = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy").format(java.time.LocalDateTime.parse(((java.lang.String)parameter_CreationDate.getValue()))); //$JR_EXPR_ID=25$
                                                                                          <--------------------->
3. java.time.format.DateTimeFormatter cannot be resolved to a type
                value = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy").format(java.time.LocalDateTime.parse(((java.lang.String)parameter_CreationDate.getValue()))); //$JR_EXPR_ID=25$
                        <-------------------------------->
4. java.time.LocalDateTime cannot be resolved to a type
                value = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy").format(java.time.LocalDateTime.parse(((java.lang.String)parameter_CreationDate.getValue()))); //$JR_EXPR_ID=25$
                                                                                          <--------------------->
5. java.time.format.DateTimeFormatter cannot be resolved to a type
                value = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy").format(java.time.LocalDateTime.parse(((java.lang.String)parameter_CreationDate.getValue()))); //$JR_EXPR_ID=25$
                        <-------------------------------->
6. java.time.LocalDateTime cannot be resolved to a type
                value = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy").format(java.time.LocalDateTime.parse(((java.lang.String)parameter_CreationDate.getValue()))); //$JR_EXPR_ID=25$
                                                                                          <--------------------->
6 errors
.
```

It there some additional configuration missing?

**Comment by voisardf** [comment]
hmm, that is strange, I tested it on my local instance without errors. Is the formatting handled the same on linux and windows @sbrunner ?

**Comment by kdeininger** [comment]
I could solve the problem by formatting the creation date in the print proxy as it is done for the footer.

**Pull request merged**
